# Generated by Django 2.1.15 on 2020-05-25 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0007_empleado_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='full_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='nombres completos'),
        ),
    ]
